### ISSUE TITLE
Welcome!

### ISSUE THREAD

**Issue by StevenCopeland** [StevenCopeland/first-timers-hacktoberfest#2]
Welcome to this repo! Please fork, create a pull request and add yourself to the list of users.

:computer: with :heart: by :bulb:

**Comment by StevenCopeland** [comment]
Check how  many PR you have gotten at: https://hacktoberfestchecker.herokuapp.com/

**Comment by Asutosh989** [comment]
Hi @StevenCopeland I have created a PR.

**Comment by StevenCopeland** [comment]
@Asutosh989 Merged your PR to master.

**Comment by imdavidy** [comment]
@StevenCopeland I think I made my pull request.

**Comment by StevenCopeland** [comment]
@imdavidy Merged your PR to master.

**Comment by vedularaghu** [comment]
Hey @StevenCopeland , please merge my PR

**Comment by StevenCopeland** [comment]
@vedularaghu Merged your PR to master

**Comment by rkpattnaik780** [comment]
Hey @StevenCopeland , plz merge my PR

**Comment by StevenCopeland** [comment]
@rkpattnaik780 Merged your PR to master

**Comment by vivekghanchi** [comment]
@StevenCopeland, when will be the Hacktoberfest t-shirt, will be given

**Comment by StevenCopeland** [comment]
I wish knew! If you find out please tell me.

**Comment by NVS16** [comment]
Hello @StevenCopeland , Made a PR. Kindly merge it. Thank You .

**Comment by StevenCopeland** [comment]
@NVS16 Merged your PR to master
